import Head from "next/head";
import Image from "next/image"; // eslint-disable-line no-unused-vars
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css"; // eslint-disable-line no-unused-vars
// import "@/styles/globals.css";
const inter = Inter({ subsets: ["latin"] }); // eslint-disable-line no-unused-vars
import HomePage from "./home";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage />
    </>
  );
}
